name: WordPress Plugin Deploy

on:
  workflow_call:
    inputs:
      build:
        default: false
        type: boolean
      php:
        default: "7.0"
        type: string
      working-directory:
        default: sdk
        type: string
      retention-days:
        default: 3
        type: number

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        if: ${{ inputs.build }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer
      - name: Install dependencies
        if: ${{ inputs.build }}
        run:
          composer install -o --no-dev
        working-directory: ${{ inputs.working-directory }}

      - name: Set Version
        if: github.event_name == 'pull_request'
        run: |
          echo "VERSION=ci" >> $GITHUB_ENV

      - name: Install Subversion
        run: sudo apt-get install subversion

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@develop
        with:
          dry-run: ${{ github.event_name == 'pull_request' }}
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ secrets.PLUGIN_SLUG }}

      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.deploy.outputs.zip-path }}
          retention-days: ${{ inputs.retention-days }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.deploy.outputs.zip-path }}
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
