name: Plugin readme update

on:
  workflow_dispatch:
    inputs:
      wp_testd_version:
        description: 'Input Tested WordPress Version'
        required: true
      wp_require_version:
        description: 'Input Require WordPress Version'
        required: false
      php_version:
        description: 'Input PHP Version'
        required: false
        default: ''

jobs:
  update:
    name: Update ${{ matrix.owner }}/${{ matrix.repository }} readme.txt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        owner: [ 'sy-records' ]
        repository: [ 'qiniu-kodo-wordpress', 'aliyun-oss-wordpress', 'sync-qcloud-cos', 'realtimehot-weibo', 'wp-baidu-textcensor', 'textcensor-for-articles', 'random-look', 'MemorialDay', 'upyun-uss-wordpress', 'volcengine-imagex-wordpress', 'huaweicloud-obs-wordpress', 'pinyin-slug', 'pangu.js', 'sy-mailer' ]
    steps:
      - uses: actions/checkout@v4

      - name: Checkout ${{ matrix.owner }}/${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.owner }}/${{ matrix.repository }}
          path: ${{ matrix.repository }}
          token: ${{ secrets.PLUGIN_GH_PAT }}

      - name: Update ${{ matrix.repository }} readme.txt
        run:
          PHP_VERSION=${{ github.event.inputs.php_version }} WP_TESTED_VERSION=${{ github.event.inputs.wp_testd_version }} WP_REQUIRE_VERSION=${{ github.event.inputs.wp_require_version }} ${{ github.workspace }}/scripts/update-plugin-readme.sh
        working-directory: ${{ matrix.repository }}

      - name: Push to ${{ matrix.owner }}/${{ matrix.repository }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ${{ matrix.repository }}
          commit_message: Update readme.txt
          file_pattern: readme.txt
          commit_options: '--signoff'
